### ISSUE TITLE
Possible to template json arrays?

### ISSUE THREAD

**Issue by dnwade** [emilsjolander/goson#6]
How would I go about rendering a field array containing, not objects, but primitives (bool, int, float, string)?

Example struct:

```
type Stats struct {
        Weights: []int
}
```

How do I convert some instance of this struct into json that looks like this?

```
{"stats": {"weights": [4,2,2] } }

```

**Comment by emilsjolander** [comment]
I made an active decision to not support this. This may change in the future but for now all items in a json array must be json objects. So your resulting json would looks something like this:

``` json
{
  "stats": {
    "weights": [
      {"weight":4},
      {"weight":2},
      {"weight":2}
    ]
  }
}
```

I made this decision because this is how most api responses look. It is also easy to add another property to the object inside the array(a timestamp or id maybe) without breaking existing clients that use the old api.

If you think this was a wrong decision to make i am glad to hear any arguments to why.

**Comment by emilsjolander** [comment]
Ok my bad. This is not supported currently, i am working on a fix! You will still need to format your json like in my previous comment but it will be possible to iterate over primitives.

**Comment by emilsjolander** [comment]
Ok i fixed the issue. I was making an unnecessary check to see if the collection to be iterated over contained anything representable as an object.

I also closed the issue but welcome a discussion to continue about supporting json collections of primitive values.

**Comment by dnwade** [comment]
It's great to be able to iterate over an array of primitives, but it's absolutely critical for me to be able to produce them in json.  How difficult is this to implement?  How much work would it take to get there?  

By the way, my use case is an api for Ember. It expects [relationship data to be sent in an array](http://emberjs.com/guides/models/connecting-to-an-http-server/).  Notice how the associated comment ids are contained in the  `post.comments` array.

**Comment by emilsjolander** [comment]
I'll get to work on it this weekend! Thanks for the feedback :+1:

**Comment by emilsjolander** [comment]
BTW. It's an easy fix so expect it by Monday or Tuesday. I want to get all the testing done before I implement anything new so that's why it will take a couple of days ;)

**Comment by emilsjolander** [comment]
Fixed! Love the feedback, you will probably (hopefully not) come into some more issues during you development with ember and i would love it if you could post all these issues here so i can fix them :) I will be pushing a test suite for goson later today or tomorrow which will make it easier for me and anyone else to make changes like this one in the future :beers:

**Comment by dnwade** [comment]
Excellent! Works perfectly

**Comment by emilsjolander** [comment]
Awesome! Just committed all the test which cover everything i could think of so you should not have any worries about using goson in production either!
